name: run cram tests

on:
  push:
  pull_request:
    branches: ["mozilla"]

jobs:
  mac:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: cmake -B build
    - name: build
      run: make -C build -j4
    - name: test
      run: |
        pip install cram
        cram test/reference/*.t
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: docker/setup-buildx-action@v3
    - name: docker build
      uses: docker/build-push-action@v6
      with:
        load: true
        tags: libdmg-hfsplus:test
    - name: test
      run: docker rm --rm libdmg-hfsplus:test
